name: Daily News Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANTE: Permiso expl√≠cito de escritura
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: pip install google-genai feedparser
      - name: Run
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_news.py
      - name: Deploy
        run: |
          git config --global user.name 'NewsBot'
          git config --global user.email 'bot@github.com'
          git add index.html
          git commit -m "Update" || exit 0
          git push
